services:
  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildFilter:
      paths:
        - frontend/**
    region: oregon
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
